# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 04 Oct 2019 01:49:27 +0000
*	@ALL	1
*	@user	1
*	@admin	16
admin:*	@ALL	0
content:*	@player	8
admin:*	@admin	1
