<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: daelmir
 * Date: Sun, 06 Oct 2019 01:12:35 +0000
 */

$conf['title'] = 'The Badlands';
$conf['template'] = 'badlands';
$conf['license'] = '0';
$conf['toptoclevel'] = '2';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = 'daelmir, ncguthwulf, thedarkstar';
$conf['manager'] = '@admin';
$conf['compress'] = 0;
$conf['proxy']['user'] = 'Daelmir';
$conf['proxy']['pass'] = '<b>QVg1MzE1MDQ0aw==';
$conf['plugin']['publish']['apr_namespaces'] = 'root wiki official admin';
$conf['plugin']['publish']['no_apr_namespaces'] = 'content';
$conf['plugin']['publish']['hide drafts'] = 1;
$conf['plugin']['publish']['hidereaderbanner'] = 1;
$conf['plugin']['publish']['hide_approved_banner'] = 1;
$conf['plugin']['publish']['author groups'] = 'admin';
$conf['plugin']['include']['noheader'] = 1;
$conf['plugin']['include']['showfooter'] = 0;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['include']['showuser'] = 0;
$conf['plugin']['include']['showcomments'] = 0;
$conf['plugin']['include']['showlinkbacks'] = 0;
$conf['plugin']['include']['showtags'] = 0;
$conf['tpl']['badlands']['subtitle'] = 'Explore the Badlands';
$conf['tpl']['gtopia']['subtitle'] = 'Explore the Badlands';
$conf['tpl']['gtopia']['disableMainImgOnSubpages'] = '1';
$conf['tpl']['gtopia']['twitter_number_of_tweets'] = '0';

// end auto-generated content
